
analysis:
  name: "PhoOnly_PromptRegions_NonCompressed_AnalysisConfig_anchor10_PtDepIsoCut"
  luminosity: 165.27
  output_json: "PhoOnly_PromptRegions_NonCompressed_AnalysisConfig_anchor10_PtDepIsoCut.json"
    
samples:
  #backgrounds: []#"Wjets", "Zjets", "QCD", "Top", "Gjets", "Box"]
  signals: ["gogoGZ"] 
  data: ["MET16","MET17","MET18","MET23"]

baseline_cuts: &baseline_cuts
  - "(selCMet > 150)" 

Cleaning: &Cleaning
  - "(Flag_MetFilters == 1) && ( rjrPTS[0] < 150) && ( (Trigger_PFMET120_PFMHT120_IDTight == 1)||(Trigger_PFMET120_PFMHT120_IDTight_PFHT60 == 1)||(Trigger_PFMETNoMu120_PFMHTNoMu120_IDTight)||(Trigger_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60))"

################################ SV VETO Strings ##################
#exactly 1 hadronic SR SV
noSV: &noSV
  - "(SV_nHadronic==0 || (SV_nHadronic == 1 && HadronicSV_dxySig[0] < 1000) || (SV_nHadronic == 2 && HadronicSV_dxySig[0] < 1000 && HadronicSV_dxySig[1] < 1000) || SV_nLeptonic==0 || (SV_nLeptonic == 1 && LeptonicSV_dxySig[0] < 1000) || (SV_nLeptonic == 2 && LeptonicSV_dxySig[0] < 1000 && LeptonicSV_dxySig[1] < 1000))"

################ Delayed photon VETO strings #########################
noBHPhotons: &noBHPhotons
  - "(( (nBaseLinePhotons == 1 && baseLinePhoton_beamHaloCNNScore[0] < 0.917252) || (nBaseLinePhotons == 2 && baseLinePhoton_beamHaloCNNScore[0] < 0.917252 && baseLinePhoton_beamHaloCNNScore[1] < 0.917252) ) )"

noNonPromptPhotons: &noNonPromptPhotons
  - "( (nBaseLinePhotons == 1 && (baseLinePhoton_WTimeSig[0] < 2.5 && baseLinePhoton_WTimeSig[0] > -2.5)) || (nBaseLinePhotons == 2 && ( baseLinePhoton_WTimeSig[0] < 2.5 && baseLinePhoton_WTimeSig[0] > -2.5) && ( baseLinePhoton_WTimeSig[1] < 2.5 && baseLinePhoton_WTimeSig[1] > -2.5)) )"
    #Ch5CReq1PhoMedIsoPrompt: &Ch5CReq1PhoMedIsoPrompt
    #  - "(nBaseLinePhotons == 1 && ((baseLinePhoton_Pt[0] > 300 && (baseLinePhoton_Eta[0] < 1.479 && baseLinePhoton_Eta[0] > -1.479 )) && baseLinePhoton_isoANNScore[0] < 0.99 ) || (nBaseLinePhotons == 2 && (baseLinePhoton_Eta[0] < 1.479 && baseLinePhoton_Eta[0] > -1.479 ) && (baseLinePhoton_Eta[1] < 1.479 && baseLinePhoton_Eta[1] > -1.479 ) && ((baseLinePhoton_isoANNScore[0] > 0.99 && baseLinePhoton_isoANNScore[1] < 0.5) || (baseLinePhoton_isoANNScore[0] < 0.99 && baseLinePhoton_isoANNScore[1] > 0.5)) && (baseLinePhoton_Pt[0] > 300 && baseLinePhoton_Pt[1] > 50) ) )"

#model iso score cut with pt-dependent linear function: m*pt - b where parameters are taken from x-range [100, 600] and y-range [cutoff, 0.9]
#cutoff slightly differs between eq1 and geq1/eq2 to better control for background (geq1 and eq2 are the same, just inverted obviously)
Ch6SReq1PhoTightIsoPrompt: &Ch6SReq1PhoTightIsoPrompt
  - "(nBaseLinePhotons == 1 && ( ((baseLinePhoton_Pt[0] > 100 && (baseLinePhoton_isoANNScore[0] >= -0.000198*baseLinePhoton_Pt[0] + 1.0188)) || (baseLinePhoton_Pt[0] <= 100 && baseLinePhoton_isoANNScore[0] >= 0.999)) && (baseLinePhoton_Eta[0] < 1.479 && baseLinePhoton_Eta[0] > -1.479) ))"
Ch6SReq2PhoTightIsoPrompt: &Ch6SReq2PhoTightIsoPrompt
  - "(nBaseLinePhotons == 2 && (((  (baseLinePhoton_Pt[0] > 100 && (baseLinePhoton_isoANNScore[0] >= -0.0001*baseLinePhoton_Pt[0] + 0.96)) || (baseLinePhoton_Pt[0] <= 100 && baseLinePhoton_isoANNScore[0] >= 0.95) ) && (baseLinePhoton_Eta[0] < 1.479 && baseLinePhoton_Eta[0] > -1.479 )) && ( (baseLinePhoton_Pt[1] > 100 && (baseLinePhoton_isoANNScore[1] >= -0.00016*baseLinePhoton_Pt[1] + 0.996)) || (baseLinePhoton_Pt[1] <= 100 && baseLinePhoton_isoANNScore[1] >= 0.98) && (baseLinePhoton_Eta[1] < 1.479 && baseLinePhoton_Eta[1] > -1.479 )) ))"
Ch5CRgeq1PhoMedIsoPrompt: &Ch5CRgeq1PhoMedIsoPrompt
  #- "(nBaseLinePhotons == 2 && ( ((  (baseLinePhoton_Pt[0] > 100 && (baseLinePhoton_isoANNScore[0] < -0.0001*baseLinePhoton_Pt[0] + 0.96) || (baseLinePhoton_Pt[0] <= 100 && baseLinePhoton_isoANNScore[0] < 0.95) ) && (baseLinePhoton_Eta[0] < 1.479 && baseLinePhoton_Eta[0] > -1.479 )) || ( (baseLinePhoton_Pt[1] > 100 && (baseLinePhoton_isoANNScore[1] < -0.00016*baseLinePhoton_Pt[1] + 0.996)) || (baseLinePhoton_Pt[1] <= 100 && baseLinePhoton_isoANNScore[1] < 0.98) && (baseLinePhoton_Eta[1] < 1.479 && baseLinePhoton_Eta[1] > -1.479 )) )) )"
  - "(( nBaseLinePhotons == 1 && ( ((baseLinePhoton_Pt[0] > 100 && (baseLinePhoton_isoANNScore[0] < -0.000198*baseLinePhoton_Pt[0] + 1.0188)) || (baseLinePhoton_Pt[0] <= 100 && baseLinePhoton_isoANNScore[0] < 0.999)) && (baseLinePhoton_Eta[0] < 1.479 && baseLinePhoton_Eta[0] > -1.479) )  ) ||  (nBaseLinePhotons == 2 && ( ((  (baseLinePhoton_Pt[0] > 100 && (baseLinePhoton_isoANNScore[0] < -0.0001*baseLinePhoton_Pt[0] + 0.96) || (baseLinePhoton_Pt[0] <= 100 && baseLinePhoton_isoANNScore[0] < 0.95) ) && (baseLinePhoton_Eta[0] < 1.479 && baseLinePhoton_Eta[0] > -1.479 )) || ( (baseLinePhoton_Pt[1] > 100 && (baseLinePhoton_isoANNScore[1] < -0.00016*baseLinePhoton_Pt[1] + 0.996)) || (baseLinePhoton_Pt[1] <= 100 && baseLinePhoton_isoANNScore[1] < 0.98) && (baseLinePhoton_Eta[1] < 1.479 && baseLinePhoton_Eta[1] > -1.479 )) )) ))"


Ch6SReq1PhoLessTightIsoPrompt: &Ch6SReq1PhoLessTightIsoPrompt
  - "(nBaseLinePhotons == 1 && ( ((baseLinePhoton_Pt[0] > 200 && (baseLinePhoton_isoANNScore[0] >= -0.0002*baseLinePhoton_Pt[0] + 1.02)) || (baseLinePhoton_Pt[0] <= 200 && baseLinePhoton_isoANNScore[0] >= 0.5)) && (baseLinePhoton_Eta[0] < 1.479 && baseLinePhoton_Eta[0] > -1.479) ))"


kin: &kin
  - "(rjr_Ms[0] >= 1000) && (rjr_Rs[0] >= 0.15)"

b00: &b00
  - "(rjr_Ms[0] >= 2500) && (rjr_Ms[0] < 3000) && (rjr_Rs[0] < 0.3)"
b10: &b10
  - "(rjr_Ms[0] >= 3000) && (rjr_Rs[0] < 0.3)"
b01: &b01
  - "(rjr_Ms[0] >= 2500) && (rjr_Ms[0] < 3000) && (rjr_Rs[0] >= 0.3)"
b11: &b11
  - "(rjr_Ms[0] >= 3000) && (rjr_Rs[0] >= 0.3)"
#add another bin that's higher in Ms-Rs for higher mass signals
b22: &b22
 - "(rjr_Ms[0] >= 3500) && (rjr_Rs[0] >= 0.4)"
    #b00: &b00
    #  - "(rjr_Ms[0] >= 2500) && (rjr_Ms[0] < 2700) && (rjr_Rs[0] < 0.3)"
    #b10: &b10
    #  - "(rjr_Ms[0] >= 2700) && (rjr_Rs[0] < 0.3)"
    #b01: &b01
    #  - "(rjr_Ms[0] >= 2500) && (rjr_Ms[0] < 2700) && (rjr_Rs[0] >= 0.3)"
    #b11: &b11
    #  - "(rjr_Ms[0] >= 2700) && (rjr_Rs[0] >= 0.3)"
    ##add another bin that's higher in Ms-Rs for higher mass signals
    #b22: &b22
    # - "(rjr_Ms[0] >= 3000) && (rjr_Rs[0] >= 0.4)"


bins:
  Ch5CRgeq1PhoMedIsoPromptBin00:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch5CRgeq1PhoMedIsoPrompt
      - *b00
  Ch5CRgeq1PhoMedIsoPromptBin10:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch5CRgeq1PhoMedIsoPrompt
      - *b10
  Ch5CRgeq1PhoMedIsoPromptBin01:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch5CRgeq1PhoMedIsoPrompt
      - *b01
  Ch5CRgeq1PhoMedIsoPromptBin11:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch5CRgeq1PhoMedIsoPrompt
      - *b11
  Ch5CRgeq1PhoMedIsoPromptBin22:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch5CRgeq1PhoMedIsoPrompt
      - *b22
  Ch6SReq1PhoTightIsoPromptBin00:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq1PhoTightIsoPrompt
      - *b00
  Ch6CReq1PhoTightIsoPromptBin10:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq1PhoTightIsoPrompt
      - *b10
  Ch6SReq1PhoTightIsoPromptBin01:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq1PhoTightIsoPrompt
      - *b01
  Ch6SReq1PhoTightIsoPromptBin11:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq1PhoTightIsoPrompt
      - *b11
  Ch6SReq1PhoTightIsoPromptBin22:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq1PhoTightIsoPrompt
      - *b22
  Ch6SReq2PhoTightIsoPromptBin00:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq2PhoTightIsoPrompt
      - *b00
  Ch6CReq2PhoTightIsoPromptBin10:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq2PhoTightIsoPrompt
      - *b10
  Ch6SReq2PhoTightIsoPromptBin01:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq2PhoTightIsoPrompt
      - *b01
  Ch6SReq2PhoTightIsoPromptBin11:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq2PhoTightIsoPrompt
      - *b11
  Ch6SReq2PhoTightIsoPromptBin22:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq2PhoTightIsoPrompt
      - *b22
  Ch6SReq1PhoLessTightIsoPromptBin00:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq1PhoLessTightIsoPrompt
      - *b00
  Ch6CReq1PhoLessTightIsoPromptBin10:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq1PhoLessTightIsoPrompt
      - *b10
  Ch6SReq1PhoLessTightIsoPromptBin01:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq1PhoLessTightIsoPrompt
      - *b01
  Ch6SReq1PhoLessTightIsoPromptBin11:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq1PhoLessTightIsoPrompt
      - *b11
  Ch6SReq1PhoLessTightIsoPromptBin22:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq1PhoLessTightIsoPrompt
      - *b22
