
analysis:
  name: "PhoOnly_PromptRegions_NonCompressed_FullRegions_AnalysisConfig_PtDepIsoCut"
  luminosity: 165.27
  output_json: "PhoOnly_PromptRegions_NonCompressed_FullRegions_AnalysisConfig_PtDepIsoCut.json"
    
samples:
  #backgrounds: []#"Wjets", "Zjets", "QCD", "Top", "Gjets", "Box"]
  signals: ["gogoGZ"] 
  data: ["MET16","MET17","MET18","MET23"]

baseline_cuts: &baseline_cuts
  - "(selCMet > 150)" 

Cleaning: &Cleaning
  - "(Flag_MetFilters == 1) && ( rjrPTS[0] < 150) && ( (Trigger_PFMET120_PFMHT120_IDTight == 1)||(Trigger_PFMET120_PFMHT120_IDTight_PFHT60 == 1)||(Trigger_PFMETNoMu120_PFMHTNoMu120_IDTight)||(Trigger_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60))"

################################ SV VETO Strings ##################
#exactly 1 hadronic SR SV
noSV: &noSV
  - "(SV_nHadronic==0 || (SV_nHadronic == 1 && HadronicSV_dxySig[0] < 1000) || (SV_nHadronic == 2 && HadronicSV_dxySig[0] < 1000 && HadronicSV_dxySig[1] < 1000) || SV_nLeptonic==0 || (SV_nLeptonic == 1 && LeptonicSV_dxySig[0] < 1000) || (SV_nLeptonic == 2 && LeptonicSV_dxySig[0] < 1000 && LeptonicSV_dxySig[1] < 1000))"

################ Delayed photon VETO strings #########################
noBHPhotons: &noBHPhotons
  - "(( (nBaseLinePhotons == 1 && baseLinePhoton_beamHaloCNNScore[0] < 0.917252) || (nBaseLinePhotons == 2 && baseLinePhoton_beamHaloCNNScore[0] < 0.917252 && baseLinePhoton_beamHaloCNNScore[1] < 0.917252) ) )"

noNonPromptPhotons: &noNonPromptPhotons
  - "( (nBaseLinePhotons == 1 && (baseLinePhoton_WTimeSig[0] < 2.5 && baseLinePhoton_WTimeSig[0] > -2.5)) || (nBaseLinePhotons == 2 && ( baseLinePhoton_WTimeSig[0] < 2.5 && baseLinePhoton_WTimeSig[0] > -2.5) && ( baseLinePhoton_WTimeSig[1] < 2.5 && baseLinePhoton_WTimeSig[1] > -2.5)) )"

#full regions: model iso score cut with pt-dependent linear function: m*pt - b where parameters are taken from x-range [100, 600] and y-range [cutoff, 0.9]
#val regions: model iso score cut with pt-dependent linear function: m*pt - b where parameters are taken from x-range [100, 400] and y-range [cutoff, 0.9]
#and obviously exclusive to full SR region
#cutoff slightly differs between eq1 and geq1/eq2 to better control for background (geq1 and eq2 are the same, just inverted obviously)
#cutoff eq1: [100, 600], [0.999, 0.95] (true SR) (slope =  -0.000198, b = 1.0188)
#cutoff eq1: [100], [0.75, 0.95) (proxy SR) (slope = -0.000198, b = 0.5198)
#
#[0.99,0.999]
Ch6SReq1PhoTightIsoPrompt: &Ch6SReq1PhoTightIsoPrompt
  #below true SR line, but above intermediate line in pt-iso score plane
  - "(nBaseLinePhotons == 1 && (baseLinePhoton_Pt[0] > 100 && (baseLinePhoton_isoANNScore[0] >= -0.000198*baseLinePhoton_Pt[0] + 1.0188)) || (baseLinePhoton_Pt[0] <= 100 && (baseLinePhoton_isoANNScore[0] >= 0.999)) && (baseLinePhoton_Eta[0] < 1.479 && baseLinePhoton_Eta[0] > -1.479))"

#[0.75,0.99]
Ch5CReq1PhoMedIsoPrompt: &Ch5CReq1PhoMedIsoPrompt
  - "(nBaseLinePhotons == 1  && ((baseLinePhoton_Pt[0] > 100 && (baseLinePhoton_isoANNScore[0] < -0.000198*baseLinePhoton_Pt[0] + 1.0188) && ( baseLinePhoton_isoANNScore[0] >= -0.000198*baseLinePhoton_Pt[0] + 0.7698)) || (baseLinePhoton_Pt[0] <= 100 && (baseLinePhoton_isoANNScore[0] < 0.999) && (baseLinePhoton_isoANNScore[0] >= 0.75)) && (baseLinePhoton_Eta[0] < 1.479 && baseLinePhoton_Eta[0] > -1.479)))"

Ch6SReq2PhoTightIsoPrompt: &Ch6SReq2PhoTightIsoPrompt
  - "(nBaseLinePhotons == 2 && (((baseLinePhoton_Pt[0] > 100 && (baseLinePhoton_isoANNScore[0] >= -0.0001*baseLinePhoton_Pt[0] + 0.96)) || (baseLinePhoton_Pt[0] <= 100 && (baseLinePhoton_isoANNScore[0] >= 0.95))) && (baseLinePhoton_Eta[0] < 1.479 && baseLinePhoton_Eta[0] > -1.479)) && ((baseLinePhoton_Pt[1] > 100 && (baseLinePhoton_isoANNScore[1] >= -0.0001*baseLinePhoton_Pt[1] + 0.96)) || (baseLinePhoton_Pt[1] <= 100 && baseLinePhoton_isoANNScore[1] >= 0.95) && (baseLinePhoton_Eta[1] < 1.479 && baseLinePhoton_Eta[1] > -1.479)))"

Ch5CReq2PhoMedIsoPrompt: &Ch5CReq2PhoMedIsoPrompt
  - "(nBaseLinePhotons == 2 && ((baseLinePhoton_Pt[0] > 100 && ( baseLinePhoton_isoANNScore[0] < -0.0001*baseLinePhoton_Pt[0] + 0.96 ) && (baseLinePhoton_isoANNScore[0] >= -0.0001*baseLinePhoton_Pt[0] + 0.76 )) || (baseLinePhoton_Pt[0] <= 100 && (baseLinePhoton_isoANNScore[0] < 0.95 && baseLinePhoton_isoANNScore[0] >= 0.75)) && (baseLinePhoton_Eta[0] < 1.479 && baseLinePhoton_Eta[0] > -1.479 )) || ((baseLinePhoton_Pt[1] > 100 && (baseLinePhoton_isoANNScore[1] < -0.0001*baseLinePhoton_Pt[1] + 0.96) && ( (baseLinePhoton_isoANNScore[1] >= -0.0001*baseLinePhoton_Pt[1] + 0.76))) || (baseLinePhoton_Pt[1] <= 100 && baseLinePhoton_isoANNScore[1] < 0.95 && baseLinePhoton_isoANNScore[1] >= 0.75) && (baseLinePhoton_Eta[1] < 1.479 && baseLinePhoton_Eta[1] > -1.479 )) )"

kin: &kin
  - "(rjr_Ms[0] >= 1000) && (rjr_Rs[0] >= 0.15)"

eq2b00: &eq2b00
  - "(rjr_Ms[0] >= 2500) && (rjr_Ms[0] < 2700) && (rjr_Rs[0] < 0.3)"
eq2b10: &eq2b10
  - "(rjr_Ms[0] >= 2700) && (rjr_Rs[0] < 0.3)"
eq2b01: &eq2b01
  - "(rjr_Ms[0] >= 2500) && (rjr_Ms[0] < 2700) && (rjr_Rs[0] >= 0.3)"
eq2b11: &eq2b11
  - "(rjr_Ms[0] >= 2700) && (rjr_Rs[0] >= 0.3)"
eq2b12: &eq2b12
  - "(rjr_Ms[0] >= 2700) && (rjr_Rs[0] >= 0.4)"

eq1b00: &eq1b00
  - "(rjr_Ms[0] >= 2700) && (rjr_Ms[0] < 3000) && (rjr_Rs[0] < 0.3)"
eq1b10: &eq1b10
  - "(rjr_Ms[0] >= 3000) && (rjr_Rs[0] < 0.3)"
eq1b01: &eq1b01
  - "(rjr_Ms[0] >= 2700) && (rjr_Ms[0] < 3000) && (rjr_Rs[0] >= 0.3) && (rjr_Rs[0] < 0.4)"
eq1b11: &eq1b11
  - "(rjr_Ms[0] >= 3000) && (rjr_Rs[0] >= 0.3) && (rjr_Rs[0] < 0.4)"
eq1b02: &eq1b02
  - "(rjr_Ms[0] >= 2700) && (rjr_Ms[0] < 3000) && (rjr_Rs[0] >= 0.4)"
eq1b22: &eq1b22
  - "(rjr_Ms[0] >= 3000) && (rjr_Rs[0] >= 0.4)"

bins:
  Ch5CReq1PhoMedIsoPromptBin00:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *kin
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch5CReq1PhoMedIsoPrompt
      - *eq1b00
  Ch5CReq1PhoMedIsoPromptBin10:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *kin
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch5CReq1PhoMedIsoPrompt
      - *eq1b10
  Ch5CReq1PhoMedIsoPromptBin01:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *kin
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch5CReq1PhoMedIsoPrompt
      - *eq1b01
  Ch5CReq1PhoMedIsoPromptBin02:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *kin
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch5CReq1PhoMedIsoPrompt
      - *eq1b02
  Ch5CReq1PhoMedIsoPromptBin11:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *kin
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch5CReq1PhoMedIsoPrompt
      - *eq1b11
  Ch5CReq1PhoMedIsoPromptBin22:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *kin
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch5CReq1PhoMedIsoPrompt
      - *eq1b22
  Ch6CReq1PhoTightIsoPromptBin00:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *kin
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq1PhoTightIsoPrompt
      - *eq1b00
  Ch6SReq1PhoTightIsoPromptBin10:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *kin
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq1PhoTightIsoPrompt
      - *eq1b10
  Ch6SReq1PhoTightIsoPromptBin01:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *kin
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq1PhoTightIsoPrompt
      - *eq1b01
 Ch6SReq1PhoTightIsoPromptBin02:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *kin
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq1PhoTightIsoPrompt
      - *eq1b02
  Ch6SReq1PhoTightIsoPromptBin22:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *kin
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq1PhoTightIsoPrompt
      - *eq1b22
  Ch6SReq1PhoTightIsoPromptBin11:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *kin
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq1PhoTightIsoPrompt
      - *eq1b11
 Ch5CReq2PhoMedIsoPromptBin00:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *kin
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch5CReq2PhoMedIsoPrompt
      - *eq1b00
  Ch5CReq2PhoMedIsoPromptBin10:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *kin
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch5CReq2PhoMedIsoPrompt
      - *eq1b10
  Ch5CReq2PhoMedIsoPromptBin01:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *kin
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch5CReq2PhoMedIsoPrompt
      - *eq1b01
  Ch5CReq2PhoMedIsoPromptBin11:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *kin
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch5CReq2PhoMedIsoPrompt
      - *eq1b11
  Ch6CReq2PhoTightIsoPromptBin00:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *kin
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq2PhoTightIsoPrompt
      - *eq1b00
  Ch6SReq2PhoTightIsoPromptBin10:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *kin
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq2PhoTightIsoPrompt
      - *eq1b10
  Ch6SReq2PhoTightIsoPromptBin01:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *kin
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq2PhoTightIsoPrompt
      - *eq1b01
  Ch6SReq2PhoTightIsoPromptBin11:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *noSV
      - *kin
      - *noBHPhotons
      - *noNonPromptPhotons
      - *Ch6SReq2PhoTightIsoPrompt
      - *eq1b11
