#test fit config
fitname: "BigGuy_NonCompressed_FullRegions_SVDelayedPhotonOnly_3BinUnblindLowMs"
asimov: True
datadriven: True

#main fit
#naming convention: Ch#[CR/SR]IDBin where Bin = xy coord in MsRs plane
shape_transfer_fit:
#main fit
#ABCD - SR bin (A) maps to [B, C, D]
#grid convention
#not bh    D | A
#        ---------
#bh        C | B
#      early -> late
# such that A*D = C*B -> A = C*B/D
ABCD_fit:
  bin_association:
    Ch13CRgeq1SVgeq1PhoBHEarlyBin:
      - "Ch13CRgeq1SVgeq1PhoBHEarlyBin00"
      - "Ch13CRgeq1SVgeq1PhoBHEarlyBin10"
      - "Ch13CRgeq1SVgeq1PhoBHEarlyBin11"
    Ch14CRgeq1SVgeq1PhoBHLateBin:
      - "Ch14CRgeq1SVgeq1PhoBHLateBin00"
      - "Ch14CRgeq1SVgeq1PhoBHLateBin10"
      - "Ch14CRgeq1SVgeq1PhoBHLateBin11"
    Ch15CRgeq1SVgeq1PhoNotBHEarlyBin:
      - "Ch15CRgeq1SVgeq1PhoNotBHEarlyBin00"
      - "Ch15CRgeq1SVgeq1PhoNotBHEarlyBin10"
      - "Ch15CRgeq1SVgeq1PhoNotBHEarlyBin11"
    Ch16SRgeq1SVgeq1PhoNotBHLateBin:
      - "Ch16SRgeq1SVgeq1PhoNotBHLateBin00"
      - "Ch16SRgeq1SVgeq1PhoNotBHLateBin10"
      - "Ch16SRgeq1SVgeq1PhoNotBHLateBin11"
  channel_association:
    Ch16SRgeq1SVgeq1PhoNotBHLateBin:
      - "Ch14CRgeq1SVgeq1PhoBHLateBin"
      - "Ch13CRgeq1SVgeq1PhoBHEarlyBin"
      - "Ch15CRgeq1SVgeq1PhoNotBHEarlyBin"
  #can add channel associations for stacked ABCD fits
#extra systematics
systematics:
  sys27:
      type: "lnN"
      name: "lnN_SignalSyst"
      init_val: 1.1
      procs:
          - "sig"
