analysis:
  name: "BigGuy_NonCompressed_SplitSVDelayedPhoton"
  luminosity: 200
  output_json: "BigGuy_NonCompressed_Validation_SVDelayedPhotonOnly_3BinMs.json"

samples:
  signals: ["gogoGZ"]
  data: ["MET16","MET17","MET18","MET22", "MET23"]

baseline_cuts: &baseline_cuts
  - "(selCMet > 150)"

Cleaning: &Cleaning
  - "((Flag_MetFilters == 1) && (rjrPTS[0] < 150) && ((Trigger_PFMET120_PFMHT120_IDTight == 1)||(Trigger_PFMET120_PFMHT120_IDTight_PFHT60 == 1)||(Trigger_PFMETNoMu120_PFMHTNoMu120_IDTight)||(Trigger_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60)))"

kin: &kin
  - "((rjr_Ms[0] >= 1500) && (rjr_Rs[0] >= 0.15))"



################################################################################################################################################################################################################################################################################################
############### SV REGIONS ###############
################################################################################################################################################################################################################################################################################################



SVgeq1Had: &SVgeq1Had
  - "((SV_nLeptonic == 0) && (SV_nHadronic >= 1))"


SVDelayedBin00: &SVDelayedBin00
  - "((rjr_Ms[0] >= 1500) && (rjr_Ms[0] < 1700) && (rjr_Rs[0] >= 0.15))"
SVDelayedBin10: &SVDelayedBin10
  - "((rjr_Ms[0] >= 1700) && (rjr_Rs[0] >= 0.15) && (rjr_Rs[0] < 0.3))"
SVDelayedBin11: &SVDelayedBin11
  - "((rjr_Ms[0] >= 1700) && (rjr_Rs[0] >= 0.3))"

eq2b00: &eq2b00

################################################################################################################################################################################################################################################################################################
############### PHOTON REGIONS ###############
################################################################################################################################################################################################################################################################################################

Ch1CRgeq1PhoBHEarly: &Ch1CRgeq1PhoBHEarly
  - "(nBaseLinePhotons > 0)"
  # >= 1 BH photon early
  - "( (nBaseLinePhotons == 1 && (baseLinePhoton_beamHaloCNNScore[0] >= 0.93 && baseLinePhoton_beamHaloCNNScore[0] < 0.9999) && baseLinePhoton_WTimeSig[0] < -2.5) || ( nBaseLinePhotons == 2 && (((baseLinePhoton_beamHaloCNNScore[0] >= 0.93 && baseLinePhoton_beamHaloCNNScore[0] < 0.9999 ) && baseLinePhoton_WTimeSig[0] < -2.5) || ((baseLinePhoton_beamHaloCNNScore[1] >= 0.93 &&  baseLinePhoton_beamHaloCNNScore[1] < 0.9999) && baseLinePhoton_WTimeSig[1] < -2.5)) ) )"

Ch2CRgeq1PhoBHLate: &Ch2CRgeq1PhoBHLate
  - "(nBaseLinePhotons > 0)"
  # >= 1 BH photon late
  - "(nBaseLinePhotons == 1 && (baseLinePhoton_beamHaloCNNScore[0] >= 0.93 && baseLinePhoton_beamHaloCNNScore[0] < 0.9999) && baseLinePhoton_WTimeSig[0] >= 2.5) || ( nBaseLinePhotons == 2 && (((baseLinePhoton_beamHaloCNNScore[0] >= 0.93 && baseLinePhoton_beamHaloCNNScore[0] < 0.9999) && baseLinePhoton_WTimeSig[0] >= 2.5) || ((baseLinePhoton_beamHaloCNNScore[1] >= 0.93 &&  baseLinePhoton_beamHaloCNNScore[1] < 0.9999) && baseLinePhoton_WTimeSig[1] >= 2.5)) )"

# ==0 BH photons
# >= 1 notBH photons
# >= 1 nonprompt
Ch3CRgeq1PhoNotBHEarly: &Ch3CRgeq1PhoNotBHEarly
  - "(nBaseLinePhotons > 0)"
  # == 0 BH photons
  - "(( (nBaseLinePhotons == 1 && baseLinePhoton_beamHaloCNNScore[0] < 0.93) || (nBaseLinePhotons == 2 && baseLinePhoton_beamHaloCNNScore[0] < 0.93 && baseLinePhoton_beamHaloCNNScore[1] < 0.93) ) )"
  # >=1 notBH photons early
  - "( (nBaseLinePhotons == 1 && (baseLinePhoton_beamHaloCNNScore[0] < 0.93 && baseLinePhoton_beamHaloCNNScore[0] >= 0.917252) && baseLinePhoton_WTimeSig[0] < -2.5) || ( nBaseLinePhotons == 2 && (((baseLinePhoton_beamHaloCNNScore[0] < 0.93 && baseLinePhoton_beamHaloCNNScore[0] >= 0.917252) && baseLinePhoton_WTimeSig[0] < -2.5) || ((baseLinePhoton_beamHaloCNNScore[1] < 0.93 && baseLinePhoton_beamHaloCNNScore[1] >= 0.917252) && baseLinePhoton_WTimeSig[1] < -2.5)) ) )"

Ch4SRgeq1PhoNotBHLate: &Ch4SRgeq1PhoNotBHLate
  - "(nBaseLinePhotons > 0)"
  # == 0 BH photons
  - "(( (nBaseLinePhotons == 1 && (baseLinePhoton_beamHaloCNNScore[0] < 0.93)) || (nBaseLinePhotons == 2 && (baseLinePhoton_beamHaloCNNScore[0] < 0.93) && (baseLinePhoton_beamHaloCNNScore[1] < 0.93)) ) )"
  # >=1 notBH photons late
  - "( (nBaseLinePhotons == 1 && (baseLinePhoton_beamHaloCNNScore[0] < 0.93 && baseLinePhoton_beamHaloCNNScore[0] >= 0.917252) && baseLinePhoton_WTimeSig[0] >= 2.5) || ( nBaseLinePhotons == 2 && (((baseLinePhoton_beamHaloCNNScore[0] < 0.93 && baseLinePhoton_beamHaloCNNScore[0] >= 0.917252) && baseLinePhoton_WTimeSig[0] >= 2.5) || ((baseLinePhoton_beamHaloCNNScore[1] < 0.93 && baseLinePhoton_beamHaloCNNScore[1] >= 0.917252) && baseLinePhoton_WTimeSig[1] >= 2.5)) ) )"

noNonPromptPhotons: &noNonPromptPhotons
  - "((nBaseLinePhotons == 0) || (nBaseLinePhotons == 1 && (baseLinePhoton_WTimeSig[0] < 2.5 && baseLinePhoton_WTimeSig[0] > -2.5)) || (nBaseLinePhotons == 2 && ( baseLinePhoton_WTimeSig[0] < 2.5 && baseLinePhoton_WTimeSig[0] > -2.5) && ( baseLinePhoton_WTimeSig[1] < 2.5 && baseLinePhoton_WTimeSig[1] > -2.5)) )"

geq1NonPromptPhotons: &geq1NonPromptPhotons
  - "( (nBaseLinePhotons == 1 && ((baseLinePhoton_WTimeSig[0] > 2.5) || (baseLinePhoton_WTimeSig[0] < -2.5))) || (nBaseLinePhotons == 2 && ( (baseLinePhoton_WTimeSig[0] > 2.5) || (baseLinePhoton_WTimeSig[0] < -2.5) || ( (baseLinePhoton_WTimeSig[1] > 2.5) || (baseLinePhoton_WTimeSig[1] < -2.5)))))"

bins:
  # ==== Ch13: Ge1 SV had Photon Early BH CR ====
  Ch13CRgeq1SVgeq1PhoBHEarlyBin00:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *kin
      - *SVgeq1Had
      - *geq1NonPromptPhotons
      - *Ch1CRgeq1PhoBHEarly
      - *SVDelayedBin00
  Ch13CRgeq1SVgeq1PhoBHEarlyBin10:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *kin
      - *SVgeq1Had
      - *geq1NonPromptPhotons
      - *Ch1CRgeq1PhoBHEarly
      - *SVDelayedBin10
  Ch13CRgeq1SVgeq1PhoBHEarlyBin11:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *kin
      - *SVgeq1Had
      - *geq1NonPromptPhotons
      - *Ch1CRgeq1PhoBHEarly
      - *SVDelayedBin11
  # ==== Ch14: Ge1 SV had Ge1 Photon Late BH CR ====
  Ch14CRgeq1SVgeq1PhoBHLateBin00:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *kin
      - *SVgeq1Had
      - *geq1NonPromptPhotons
      - *Ch2CRgeq1PhoBHLate
      - *SVDelayedBin00
  Ch14CRgeq1SVgeq1PhoBHLateBin10:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *kin
      - *SVgeq1Had
      - *geq1NonPromptPhotons
      - *Ch2CRgeq1PhoBHLate
      - *SVDelayedBin10
  Ch14CRgeq1SVgeq1PhoBHLateBin11:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *kin
      - *SVgeq1Had
      - *geq1NonPromptPhotons
      - *Ch2CRgeq1PhoBHLate
      - *SVDelayedBin11
  # ==== Ch15: Ge1 SV had Ge1 Photon Early !BH CR ====
  Ch15CRgeq1SVgeq1PhoNotBHEarlyBin00:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *kin
      - *SVgeq1Had
      - *geq1NonPromptPhotons
      - *Ch3CRgeq1PhoNotBHEarly
      - *SVDelayedBin00
  Ch15CRgeq1SVgeq1PhoNotBHEarlyBin10:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *kin
      - *SVgeq1Had
      - *geq1NonPromptPhotons
      - *Ch3CRgeq1PhoNotBHEarly
      - *SVDelayedBin10
  Ch15CRgeq1SVgeq1PhoNotBHEarlyBin11:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *kin
      - *SVgeq1Had
      - *geq1NonPromptPhotons
      - *Ch3CRgeq1PhoNotBHEarly
      - *SVDelayedBin11
  # ==== Ch16: Ge1 SV had Ge1 Photon Late !BH SR ====
  Ch16SRgeq1SVgeq1PhoNotBHLateBin00:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *kin
      - *SVgeq1Had
      - *geq1NonPromptPhotons
      - *Ch4SRgeq1PhoNotBHLate
      - *SVDelayedBin00
  Ch16SRgeq1SVgeq1PhoNotBHLateBin10:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *kin
      - *SVgeq1Had
      - *geq1NonPromptPhotons
      - *Ch4SRgeq1PhoNotBHLate
      - *SVDelayedBin10
  Ch16SRgeq1SVgeq1PhoNotBHLateBin11:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *kin
      - *SVgeq1Had
      - *geq1NonPromptPhotons
      - *Ch4SRgeq1PhoNotBHLate
      - *SVDelayedBin11



