#test fit config
fitname: "PhoOnly_DelayedRegions_NonCompressed_FullRegions"
asimov: True
datadriven: True

#main fit
#naming convention: Ch#[CR/SR]IDBin where Bin = xy coord in MsRs plane
shape_transfer_fit:

#main fit
#ABCD - SR bin (A) maps to [B, C, D]
#grid convention
#not bh    D | A
#        ---------
#bh        C | B
#      early -> late
# such that A*D = C*B -> A = C*B/D
ABCD_fit:
  bin_association:
    Ch1CRgeq1PhoBHEarly:
      - "Ch1CRgeq1PhoBHEarlyBin00"
    Ch2CRgeq1PhoBHLate:
      - "Ch2CRgeq1PhoBHLateBin00"
    Ch3CRgeq1PhoNotBHEarly:
      - "Ch3CRgeq1PhoNotBHEarlyBin00"
    Ch4SRgeq1PhoNotBHLate:
      - "Ch4SRgeq1PhoNotBHLateBin00"
  channel_association:
    Ch4SRgeq1PhoNotBHLate:
      - "Ch2CRgeq1PhoBHLate"
      - "Ch1CRgeq1PhoBHEarly"
      - "Ch3CRgeq1PhoNotBHEarly"
  #can add channel associations for stacked ABCD fits
#extra systematics
systematics:
  #pin CR channels
  sys5:
      type: "lnN"
      name: "lnN_Ch1CRgeq1PhoBHEarly"
      init_val: 1.05
      bins:
        - "Ch1CRgeq1PhoBHEarlyBin00"
  sys6:
      type: "lnN"
      name: "lnN_Ch2CRgeq1PhoBHLate"
      init_val: 1.05
      bins:
        - "Ch2CRgeq1PhoBHLateBin00"
  sys7:
      type: "lnN"
      name: "lnN_Ch3CRgeq1PhoNotBHEarly"
      init_val: 1.05
      bins:
        - "Ch3CRgeq1PhoNotBHEarlyBin00"
  sys8:
      type: "lnN"
      name: "lnN_Ch4SRgeq1PhoNotBHLate"
      init_val: 1.5
      bins:
        - "Ch4SRgeq1PhoNotBHLateBin00"
