#test fit config
fitname: "PhoDelayedPrompt_SVHad_ValidationRegions_noAsimov"
asimov: False
datadriven: True

#main fit
#naming convention: Ch#[CR/SR]IDBin where Bin = xy coord in MsRs plane
shape_transfer_fit:
  bin_association:
    Ch5CRPho1Iso:
      - "Ch5CRPho1Iso00"
      - "Ch5CRPho1Iso01"
      - "Ch5CRPho1Iso10"
      - "Ch5CRPho1Iso11"
    Ch6CRPho2Iso:
      - "Ch6CRPho2Iso00"
      - "Ch6CRPho2Iso01"
      - "Ch6CRPho2Iso10"
      - "Ch6CRPho2Iso11"
    Ch7CRHadLow:
      - "Ch7CRHadLow00"
      - "Ch7CRHadLow01"
      - "Ch7CRHadLow10"
      - "Ch7CRHadLow11"
    Ch8CRHadHigh:
      - "Ch8CRHadHigh00"
      - "Ch8CRHadHigh01"
      - "Ch8CRHadHigh10"
      - "Ch8CRHadHigh11"
  channel_association:
    Ch5CRPho1Iso:
      - "Ch6CRPho2Iso"
    Ch7CRHadLow: #anchor
      - "Ch8CRHadHigh" #buoy
  anchor_bin: "01"
#main fit
#ABCD - SR bin (A) maps to [B, C, D]
#grid convention
#not bh    D | A
#        ---------
#bh        C | B
#      early -> late
# such that A*D = C*B -> A = C*B/D
ABCD_fit:
  bin_association:
    Ch1CRPhoBHEarly:
      - "Ch1CRPhoBHEarly00"
      - "Ch1CRPhoBHEarly10"
    Ch2CRPhoBHLate:
      - "Ch2CRPhoBHLate00"
      - "Ch2CRPhoBHLate10"
    Ch3CRPhonotBHEarly:
      - "Ch3CRPhonotBHEarly00"
      - "Ch3CRPhonotBHEarly10"
    Ch4CRPhonotBHLate:
      - "Ch4CRPhonotBHLate00"
      - "Ch4CRPhonotBHLate10"
  channel_association:
    Ch4CRPhonotBHLate:
      - "Ch2CRPhoBHLate"
      - "Ch1CRPhoBHEarly"
      - "Ch3CRPhonotBHEarly"
  #can add channel associations for stacked ABCD fits
#extra systematics
systematics:
  #pin CR channels
  sys1:
      type: "lnN"
      name: "lnN_Ch5Ch6Shape00"
      init_val: 1.1 
      bins:
          - "Ch5CRPho1Iso00"
          - "Ch6CRPho2Iso00"
  sys2:
      type: "lnN"
      name: "lnN_Ch5Ch6Shape01"
      init_val: 1.1 
      bins:
          - "Ch5CRPho1Iso01"
          - "Ch6CRPho2Iso01"
  sys3:
      type: "lnN"
      name: "lnN_Ch5Ch6Shape10"
      init_val: 1.05 
      bins:
          - "Ch5CRPho1Iso10"
          - "Ch6CRPho2Iso10"
  sys3p1:
      type: "lnN"
      name: "lnN_Ch5Shape01"
      init_val: 1.05 
      bins:
          - "Ch5CRPho1Iso01"
  sys3p2:
      type: "lnN"
      name: "lnN_Ch6Shape01"
      init_val: 1.05 
      bins:
          - "Ch6CRPho2Iso01"
  sys4:
      type: "lnN"
      name: "lnN_Ch5Ch6Shape11"
      init_val: 1.1 
      bins:
          - "Ch5CRPho1Iso11"
          - "Ch6CRPho2Iso11"
  sys5:
      type: "lnN"
      name: "lnN_Ch1CRPhoBHEarly"
      init_val: 1.05
      bins:
        - "Ch1CRPhoBHEarly00"
        - "Ch1CRPhoBHEarly10"
  sys6:
      type: "lnN"
      name: "lnN_Ch2CRPhoBHLate"
      init_val: 1.1
      bins:
        - "Ch2CRPhoBHLate00"
        - "Ch2CRPhoBHLate10"
  sys7:
      type: "lnN"
      name: "lnN_Ch3CRPhonotBHEarly"
      init_val: 1.05
      bins:
        - "Ch3CRPhonotBHEarly00"
        - "Ch3CRPhonotBHEarly10"
  sys8:
      type: "lnN"
      name: "lnN_Ch4CRPhonotBHLate"
      init_val: 1.3
      bins:
        - "Ch4CRPhonotBHLate00"
        - "Ch4CRPhonotBHLate10"
  sys8p1:
      type: "lnN"
      name: "lnN_Ch4CRPhonotBHLate00"
      init_val: 1.1
      bins:
        - "Ch4CRPhonotBHLate00"
  sys8p2:
      type: "lnN"
      name: "lnN_Ch4CRPhonotBHLate10"
      init_val: 1.3
      bins:
        - "Ch4CRPhonotBHLate10"
  sys9:
      type: "lnN"
      name: "lnN_Ch7Ch8Shape00"
      init_val: 1.3
      bins:
          - "Ch7CRHadLow00"
          - "Ch8CRHadHigh00"
  sys10:
      type: "lnN"
      name: "lnN_Ch7Ch8Shape01"
      init_val: 1.2
      bins:
          - "Ch7CRHadLow01"
          - "Ch8CRHadHigh01"
  sys11:
      type: "lnN"
      name: "lnN_Ch7Ch8Shape10"
      init_val: 1.3
      bins:
          - "Ch7CRHadLow10"
          - "Ch8CRHadHigh10"
  sys12:
      type: "lnN"
      name: "lnN_Ch7Ch8Shape11"
      init_val: 1.05
      bins:
          - "Ch7CRHadLow11"
          - "Ch8CRHadHigh11"
  sys13:
      type: "lnN"
      name: "lnN_AnchorError"
      init_val: 1.10
      bins:
          - "Ch7CRHadLow01"
