# Simple two-channel, four-bin analysis for had SVs and photons
# validation fit: CR -> CR 

analysis:
  name: "Pho2Prompt_Compressed_v49"
  luminosity: 165.27
  output_json: "Pho2Prompt_FullRegions_Compressed_v49.json"

samples:
  #backgrounds: []#"Wjets", "Zjets", "QCD", "Top", "Gjets", "Box"]
  signals: ["gogoGZ"] 
  data: ["MET16","MET17","MET18","MET23"]

baseline_cuts: &baseline_cuts
  - "(selCMet > 150)" 

################################ SV Strings ##################

  - "SV_nHadronic==0 || (SV_nHadronic == 1 && HadronicSV_dxySig[0] < 1000)"
noSVhad2: &noSVhad2
  - "SV_nHadronic==0 || (SV_nHadronic == 2 && HadronicSV_dxySig[0] < 1000 && HadronicSV_dxySig[1] < 1000)"

noSVlep1: &noSVlep1
  - "SV_nLeptonic==0 || (SV_nLeptonic == 1 && LeptonicSV_dxySig[0] < 1000)"
noSVlep2: &noSVlep2
  - "SV_nLeptonic==0 || (SV_nLeptonic == 2 && LeptonicSV_dxySig[0] < 1000 && LeptonicSV_dxySig[1] < 1000)"

noSV: &noSV
  - "(SV_nHadronic==0 || (SV_nHadronic == 1 && HadronicSV_dxySig[0] < 1000) || (SV_nHadronic == 2 && HadronicSV_dxySig[0] < 1000 && HadronicSV_dxySig[1] < 1000) || SV_nLeptonic==0 || (SV_nLeptonic == 1 && LeptonicSV_dxySig[0] < 1000) || (SV_nLeptonic == 2 && LeptonicSV_dxySig[0] < 1000 && LeptonicSV_dxySig[1] < 1000))"

noSVhad: &noSVhad
  - "SV_nHadronic==0 || (SV_nHadronic == 1 && HadronicSV_dxySig[0] < 1000) || (SV_nHadronic == 2 && HadronicSV_dxySig[0] < 1000 && HadronicSV_dxySig[1] < 1000)"

noSVlep: &noSVlep
  - "SV_nLeptonic==0 || (SV_nLeptonic == 1 && LeptonicSV_dxySig[0] < 1000) || (SV_nLeptonic == 2 && LeptonicSV_dxySig[0] < 1000 && LeptonicSV_dxySig[1] < 1000)"

################################################################

############################### Photon Strings ##########################

noTightPrompt1: &noTightPrompt1
  - "nBaseLinePhotons == 0 || (nBaseLinePhotons ==1 && baseLinePhoton_isoANNScore[0]< 0.9 && baseLinePhoton_WTimeSig[0]  < 2.5 && baseLinePhoton_WTimeSig[0] > -2.5)"

noTightPrompt2: &noTightPrompt2
  - "nBaseLinePhotons == 0 || (nBaseLinePhotons ==2 && baseLinePhoton_isoANNScore[0]< 0.9 && baseLinePhoton_WTimeSig[0]  < 2.5 && baseLinePhoton_WTimeSig[0] > -2.5 && baseLinePhoton_isoANNScore[1]< 0.9 && baseLinePhoton_WTimeSig[1]  < 2.5 && baseLinePhoton_WTimeSig[1] > -2.5)"


noNotBHLate1: &noNotBHLate1
  - "nBaseLinePhotons == 0 || (nBaseLinePhotons==1 && baseLinePhoton_beamHaloCNNScore[0]>0.185 && baseLinePhoton_WTimeSig[0]  >= 2.5)"

noNotBHLate2: &noNotBHLate2
  - "nBaseLinePhotons == 0 || (nBaseLinePhotons==2 && baseLinePhoton_beamHaloCNNScore[0]>0.185 && baseLinePhoton_WTimeSig[0]  >= 2.5 && baseLinePhoton_beamHaloCNNScore[1]>0.185 && baseLinePhoton_WTimeSig[1]  >= 2.5)"

noTightPrompt: &noTightPrompt
  - "( nBaseLinePhotons == 0 || (nBaseLinePhotons ==1 && baseLinePhoton_isoANNScore[0]< 0.9 && baseLinePhoton_WTimeSig[0]  < 2.5 && baseLinePhoton_WTimeSig[0] > -2.5) || (nBaseLinePhotons ==2 && baseLinePhoton_isoANNScore[0]< 0.9 && baseLinePhoton_WTimeSig[0]  < 2.5 && baseLinePhoton_WTimeSig[0] > -2.5 && baseLinePhoton_isoANNScore[1]< 0.9 && baseLinePhoton_WTimeSig[1]  < 2.5 && baseLinePhoton_WTimeSig[1] > -2.5) )"

noNotBHLate: &noNotBHLate
  - "( nBaseLinePhotons == 0 || (nBaseLinePhotons==1 && baseLinePhoton_beamHaloCNNScore[0]>0.185 && baseLinePhoton_WTimeSig[0]  >= 2.5) || (nBaseLinePhotons==2 && baseLinePhoton_beamHaloCNNScore[0]>0.185 && baseLinePhoton_WTimeSig[0]  >= 2.5 && baseLinePhoton_beamHaloCNNScore[1]>0.185 && baseLinePhoton_WTimeSig[1]  >= 2.5) )"

noSigPhoton: &noSigPhoton
  - "( nBaseLinePhotons == 0 || (nBaseLinePhotons ==1 && baseLinePhoton_isoANNScore[0]< 0.9 && baseLinePhoton_WTimeSig[0]  < 2.5 && baseLinePhoton_WTimeSig[0] > -2.5) || (nBaseLinePhotons ==2 && baseLinePhoton_isoANNScore[0]< 0.9 && baseLinePhoton_WTimeSig[0]  < 2.5 && baseLinePhoton_WTimeSig[0] > -2.5 && baseLinePhoton_isoANNScore[1]< 0.9 && baseLinePhoton_WTimeSig[1]  < 2.5 && baseLinePhoton_WTimeSig[1] > -2.5) || (nBaseLinePhotons==1 && baseLinePhoton_beamHaloCNNScore[0]>0.185 && baseLinePhoton_WTimeSig[0]  >= 2.5) || (nBaseLinePhotons==2 && baseLinePhoton_beamHaloCNNScore[0]>0.185 && baseLinePhoton_WTimeSig[0]  >= 2.5 && baseLinePhoton_beamHaloCNNScore[1]>0.185 && baseLinePhoton_WTimeSig[1]  >= 2.5) )"

####mixed
#equals 1 baseline prompt and equals 1 sv hadronic
#CR of geq1 and ge1; geq1 photon prompt both CR, geq1 SVhad both CR
PhoCR_geq1prompt: &PhoCR_geq1prompt
  - " ((nBaseLinePhotons == 1 && baseLinePhoton_isoANNScore[0]< 0.9 && baseLinePhoton_WTimeSig[0]  < 2.5 && baseLinePhoton_WTimeSig[0] > -2.5) ||  (nBaseLinePhotons ==2 && baseLinePhoton_isoANNScore[0]< 0.9 && baseLinePhoton_WTimeSig[0]  < 2.5 && baseLinePhoton_WTimeSig[0] > -2.5 && baseLinePhoton_isoANNScore[1]< 0.9 && baseLinePhoton_WTimeSig[1]  < 2.5 && baseLinePhoton_WTimeSig[1] > -2.5))" 

PhoSR_geq2prompt: &PhoSR_geq2prompt
  - " (  ( nBaseLinePhotons ==2 &&  (baseLinePhoton_isoANNScore[0]> 0.9 && baseLinePhoton_isoANNScore[1]>0.9) && baseLinePhoton_WTimeSig[0]  < 2.5 && baseLinePhoton_WTimeSig[0] > -2.5 && baseLinePhoton_WTimeSig[1]  < 2.5 && baseLinePhoton_WTimeSig[1] > -2.5) )"   

geq1PhoPromptCR: &geq1PhoPromptCR
  - " ( (nBaseLinePhotons == 1 && baseLinePhoton_isoANNScore[0]< 0.9 &&  baseLinePhoton_WTimeSig[0] > 0) ||  (nBaseLinePhotons == 2 && baseLinePhoton_isoANNScore[0]< 0.9  && baseLinePhoton_isoANNScore[1]< 0.9 &&  baseLinePhoton_WTimeSig[0] > 0 &&  baseLinePhoton_WTimeSig[1] > 0))" 

geq1PhoPromptSR: &geq1PhoPromptSR
  - " ( (nBaseLinePhotons == 1 && baseLinePhoton_isoANNScore[0]> 0.95 && baseLinePhoton_WTimeSig[0] > 0) ||  (nBaseLinePhotons == 2 && baseLinePhoton_isoANNScore[0]> 0.95  && baseLinePhoton_isoANNScore[1]> 0.95 && baseLinePhoton_WTimeSig[0] > 0 && baseLinePhoton_WTimeSig[1] > 0))"




##########################################################
Cleaning: &Cleaning
  - "(Flag_MetFilters == 1)  && ( (Trigger_PFMET120_PFMHT120_IDTight == 1)||(Trigger_PFMET120_PFMHT120_IDTight_PFHT60 == 1)||(Trigger_PFMETNoMu120_PFMHTNoMu120_IDTight)||(Trigger_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60))"
    

kin: &kin
  - "(rjrIsrNPhotons > rjrIsrNISRPhos) && rjrIsr_nSVisObjects > 2 && rjrIsr_PtIsr > 800"

b00: &b00
  - "(rjrIsr_RIsr >= 0.7) && (rjrIsr_RIsr < 0.8)"
b10: &b10
  - "(rjrIsr_RIsr >= 0.8) && (rjrIsr_RIsr < 0.9)"
    #b21: &b20
    #  - "(rjrIsr_RIsr >= 0.9)"

bins:
  Ch1CRgeq1Pho00:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *PhoCR_geq1prompt
      - *noSV
      - *kin
      - *b00
  Ch1CRgeq1Pho10:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *PhoCR_geq1prompt
      - *noSV
      - *kin
      - *b10
        #  Ch1CRgeq1Pho20:
        #    cuts:
        #      - *baseline_cuts
        #      - *Cleaning
        #      - *PhoCR_geq1prompt
        #      - *noSV
        #      - *kin
        #      - *b20
  
  Ch2CRgeq1Pho00:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *PhoSR_geq2prompt
      - *noSV
      - *kin
      - *b00
  Ch2SRgeq1Pho10:
    cuts:
      - *baseline_cuts
      - *Cleaning
      - *PhoSR_geq2prompt
      - *noSV
      - *kin
      - *b10
        #  Ch2SRgeq1Pho20:
        #    cuts:
        #      - *baseline_cuts
        #      - *Cleaning
        #      - *PhoSR_geq2prompt
        #      - *noSV
        #      - *kin
        #      - *b20

