# Simple two-channel, four-bin analysis for had SVs and photons
# validation fit: CR -> CR 

analysis:
  name: "SV_FullRegions_noMix_NonCompressed_v49_MConly"
  luminosity: 1600.0
  output_json: "SV_FullRegions_noMix_NonCompressed_SMSOnlyPureZZ_v49.json"

samples:
  #backgrounds: []#"Wjets", "Zjets", "QCD", "Top", "Gjets", "Box"]
  signals: ["gogoGZ"] 
    #data: ["MET23"]

baseline_cuts: &baseline_cuts
  - "(selCMet > 150) && (Evt_isZZ == 1)" 

nHad1: &nHad1
  - "(SV_nHadronic == 1)"

#dxy sideband
CRLowdxyHad: &CRLowdxyHad
  - "(HadronicSV_dxySig[0] < 1000)"
  
#dxy signal region
SRHighdxyHad: &SRHighdxyHad
  - "(HadronicSV_dxySig[0] >= 1000)"

Cleaning: &Cleaning
  - "(Flag_MetFilters == 1) && ( rjrPTS[0] < 150) && ( (Trigger_PFMET120_PFMHT120_IDTight == 1)||(Trigger_PFMET120_PFMHT120_IDTight_PFHT60 == 1)||(Trigger_PFMETNoMu120_PFMHTNoMu120_IDTight)||(Trigger_PFMETNoMu120_PFMHTNoMu120_IDTight_PFHT60))"
    
kin: &kin
  - "(rjr_Ms[0] >= 1000) && (rjr_Rs[0] >= 0.15)"

b00: &b00
  - "(rjr_Ms[0] >= 2000) && (rjr_Ms[0] < 2700) && (rjr_Rs[0] < 0.3)"
b10: &b10
  - "(rjr_Ms[0] >= 2700) && (rjr_Rs[0] < 0.3)"
b01: &b01
  - "(rjr_Ms[0] >= 2000) && (rjr_Ms[0] < 2700) && (rjr_Rs[0] >= 0.3)"
b11: &b11
  - "(rjr_Ms[0] >= 2700) && (rjr_Rs[0] >= 0.3)"


bins:
  Ch7CRSVHadLowDxy00:
    cuts:
      - *baseline_cuts
      - *CRLowdxyHad
      - *nHad1
      - *Cleaning
      - *kin
      - *b00
  Ch7CRSVHadLowDxy10:
      - *baseline_cuts
      - *nHad1
      - *CRLowdxyHad
      - *Cleaning
      - *kin
      - *b10
  Ch7CRSVHadLowDxy01:
      - *baseline_cuts
      - *nHad1
      - *CRLowdxyHad
      - *Cleaning
      - *kin
      - *b01
  Ch7CRSVHadLowDxy11:
      - *baseline_cuts
      - *nHad1
      - *CRLowdxyHad
      - *Cleaning
      - *kin
      - *b11

  Ch8CRSVHadHighDxy00:
    cuts:
      - *baseline_cuts
      - *SRHighdxyHad
      - *nHad1
      - *Cleaning
      - *kin
      - *b00
  Ch8SRSVHadHighDxy10:
      - *baseline_cuts
      - *nHad1
      - *SRHighdxyHad
      - *Cleaning
      - *kin
      - *b10
  Ch8SRSVHadHighDxy01:
      - *baseline_cuts
      - *nHad1
      - *SRHighdxyHad
      - *Cleaning
      - *kin
      - *b01
  Ch8SRSVHadHighDxy11:
      - *baseline_cuts
      - *nHad1
      - *SRHighdxyHad
      - *Cleaning
      - *kin
      - *b11

  
